// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRInteraction : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ACTION
        {
            get
            {
                return SteamVR_Actions.vRInteraction_ACTION;
            }
        }
        
        public virtual SteamVR_Action_Boolean PICKUP_DROP
        {
            get
            {
                return SteamVR_Actions.vRInteraction_PICKUP_DROP;
            }
        }
        
        public virtual SteamVR_Action_Boolean PICKUP
        {
            get
            {
                return SteamVR_Actions.vRInteraction_PICKUP;
            }
        }
        
        public virtual SteamVR_Action_Boolean DROP
        {
            get
            {
                return SteamVR_Actions.vRInteraction_DROP;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.vRInteraction_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.vRInteraction_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.vRInteraction_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerPressure
        {
            get
            {
                return SteamVR_Actions.vRInteraction_TriggerPressure;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchPosition
        {
            get
            {
                return SteamVR_Actions.vRInteraction_TouchPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadTouched
        {
            get
            {
                return SteamVR_Actions.vRInteraction_PadTouched;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadPressed
        {
            get
            {
                return SteamVR_Actions.vRInteraction_PadPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean BUTTON_1
        {
            get
            {
                return SteamVR_Actions.vRInteraction_BUTTON_1;
            }
        }
        
        public virtual SteamVR_Action_Boolean BUTTON_2
        {
            get
            {
                return SteamVR_Actions.vRInteraction_BUTTON_2;
            }
        }
        
        public virtual SteamVR_Action_Boolean BUTTON_3
        {
            get
            {
                return SteamVR_Actions.vRInteraction_BUTTON_3;
            }
        }
        
        public virtual SteamVR_Action_Boolean BUTTON_4
        {
            get
            {
                return SteamVR_Actions.vRInteraction_BUTTON_4;
            }
        }
        
        public virtual SteamVR_Action_Boolean TELEPORT
        {
            get
            {
                return SteamVR_Actions.vRInteraction_TELEPORT;
            }
        }
        
        public virtual SteamVR_Action_Boolean SWITCH
        {
            get
            {
                return SteamVR_Actions.vRInteraction_SWITCH;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.vRInteraction_Haptic;
            }
        }
    }
}
